/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
 * Generated on: 04-Jun-2020 13:37:19
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019a\extern\include\tmwtypes.h 
 */
const int num_coefficients = 30;
const real32_T coefficients[30] = {
   0.001660885755, 0.001669131219,-0.0003099146998,-0.004270857666, -0.00634398777,
  -0.0005407619174,  0.01264786068,   0.0203030128,  0.00594812585, -0.02935836092,
    -0.0549142547, -0.02712169848,  0.07165023685,   0.2060391754,   0.3029414117,
     0.3029414117,   0.2060391754,  0.07165023685, -0.02712169848,  -0.0549142547,
   -0.02935836092,  0.00594812585,   0.0203030128,  0.01264786068,-0.0005407619174,
   -0.00634398777,-0.004270857666,-0.0003099146998, 0.001669131219, 0.001660885755
};
