/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
 * Generated on: 04-Jun-2020 13:39:01
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019a\extern\include\tmwtypes.h 
 */
const int num_coefficients = 30;
const real32_T coefficients[30] = {
   0.001230077818,-0.0004656519159,-0.001785991597,-0.001315643196,  0.00219952222,
   0.006215703674, 0.002844037721, -0.01646158099, -0.05142180994, -0.08645879477,
   -0.09540998191, -0.05775989592,  0.02379585057,   0.1185133532,   0.1819779277,
     0.1819779277,   0.1185133532,  0.02379585057, -0.05775989592, -0.09540998191,
   -0.08645879477, -0.05142180994, -0.01646158099, 0.002844037721, 0.006215703674,
    0.00219952222,-0.001315643196,-0.001785991597,-0.0004656519159, 0.001230077818
};
