/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.6 and DSP System Toolbox 9.8.
 * Generated on: 04-Jun-2020 14:02:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 4)
 * Arithmetic        : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2019a\extern\include\tmwtypes.h 
 */
const int num_coefficients = 30;
const real32_T coefficients[30] = {
  0.0005600868608,-0.001335998997,-0.003108558245,-0.002197619528, 0.003676217049,
    0.01087517012, 0.009126743302,-0.007997745648, -0.02953224443, -0.02874099091,
    0.01258006506,  0.07479119301,  0.09494045377, -0.01549747214,  -0.5583462119,
     0.5583462119,  0.01549747214, -0.09494045377, -0.07479119301, -0.01258006506,
    0.02874099091,  0.02953224443, 0.007997745648,-0.009126743302, -0.01087517012,
  -0.003676217049, 0.002197619528, 0.003108558245, 0.001335998997,-0.0005600868608
};
